from __future__ import annotations

import threading
from contextlib import contextmanager
from typing import Any, Iterator

import psycopg
from psycopg.rows import dict_row

from usage.constants.constants import Constants
from usage.libraries.crypto_box import CryptoBox
from usage.structures.settings import Settings


class Database:
    def __init__(self, settings: Settings) -> None:
        self._database_url = settings.database_url
        self._crypto = CryptoBox(settings.encryption_key)
        # Thread-local: each FastAPI worker thread reuses one connection across requests
        # instead of opening a new TCP connection per query.
        self._local = threading.local()

    @property
    def database_url(self) -> str:
        return self._database_url

    def initialize(self) -> None:
        with self.transaction():
            connection = self._connection()
            self._create_schema(connection)
            self._migrate(connection)
            self._seed(connection)

    def health(self) -> bool:
        row = self.fetch_one("SELECT 1 AS ok")
        return row is not None and int(row["ok"]) == 1

    @contextmanager
    def transaction(self) -> Iterator[None]:
        """Run the enclosed statements atomically on this thread's connection."""
        connection = self._connection()
        self._local.transaction_depth = self._transaction_depth() + 1
        try:
            with connection.transaction():
                yield
        finally:
            self._local.transaction_depth = self._transaction_depth() - 1

    def _connection(self) -> psycopg.Connection[dict[str, Any]]:
        result = getattr(self._local, "connection", None)
        if result is None or result.closed:
            result = psycopg.connect(self._database_url, row_factory=dict_row)
            self._local.connection = result
        return result

    def _transaction_depth(self) -> int:
        return int(getattr(self._local, "transaction_depth", 0))

    def _run(self, query: str, parameters: tuple[Any, ...]) -> psycopg.Cursor[dict[str, Any]]:
        connection = self._connection()
        try:
            return connection.execute(query, parameters)
        except psycopg.OperationalError:
            if self._transaction_depth() > 0:
                raise
            # The pooled connection died (server restart, dropped socket): reconnect once.
            connection.close()
            return self._connection().execute(query, parameters)
        except psycopg.Error:
            if self._transaction_depth() == 0:
                connection.rollback()
            raise

    def _finish(self) -> None:
        if self._transaction_depth() == 0:
            self._connection().commit()

    def encrypt(self, value: str) -> str:
        return self._crypto.encrypt(value)

    def decrypt(self, value: str) -> str:
        return self._crypto.decrypt(value)

    def blind_index(self, value: str) -> str:
        return self._crypto.blind_index(value)

    def decrypt_row(self, row: dict[str, Any], fields: tuple[str, ...]) -> dict[str, Any]:
        result = dict(row)
        for field in fields:
            if field in result:
                result[field] = self.decrypt(str(result[field] or ""))
        return result

    def decrypt_rows(self, rows: list[dict[str, Any]], fields: tuple[str, ...]) -> list[dict[str, Any]]:
        return [self.decrypt_row(row, fields) for row in rows]

    def fetch_all(self, query: str, parameters: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
        rows = self._run(query, parameters).fetchall()
        self._finish()
        return [dict(row) for row in rows]

    def fetch_one(self, query: str, parameters: tuple[Any, ...] = ()) -> dict[str, Any] | None:
        row = self._run(query, parameters).fetchone()
        self._finish()
        if row is None:
            return None
        return dict(row)

    def execute(self, query: str, parameters: tuple[Any, ...] = ()) -> int:
        cursor = self._run(query, parameters)
        row = cursor.fetchone() if cursor.description else None
        self._finish()
        if row is None:
            return 0
        return int(row["id"])

    def _create_schema(self, connection: psycopg.Connection[dict[str, Any]]) -> None:
        statements: list[str] = [
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email_sealed TEXT NOT NULL,
                email_hash TEXT NOT NULL UNIQUE,
                name_sealed TEXT NOT NULL DEFAULT '',
                is_admin BOOLEAN NOT NULL DEFAULT false,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                last_login_at TIMESTAMPTZ
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS houses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name_sealed TEXT NOT NULL,
                timezone TEXT NOT NULL DEFAULT 'Europe/Paris',
                ingest_token_hash TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS user_houses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                house_id BIGINT NOT NULL REFERENCES houses(id) ON DELETE CASCADE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE(user_id, house_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS meters (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                house_id BIGINT NOT NULL REFERENCES houses(id) ON DELETE CASCADE,
                kind TEXT NOT NULL,
                label_sealed TEXT NOT NULL,
                unit TEXT NOT NULL DEFAULT '',
                monthly BOOLEAN NOT NULL DEFAULT false,
                position INTEGER NOT NULL DEFAULT 0,
                active BOOLEAN NOT NULL DEFAULT true,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS registers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                meter_id BIGINT NOT NULL REFERENCES meters(id) ON DELETE CASCADE,
                label_sealed TEXT NOT NULL DEFAULT '',
                initial_value NUMERIC(12,3) NOT NULL DEFAULT 0,
                position INTEGER NOT NULL DEFAULT 0,
                active BOOLEAN NOT NULL DEFAULT true,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS readings (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                meter_id BIGINT NOT NULL REFERENCES meters(id) ON DELETE CASCADE,
                read_on DATE NOT NULL,
                source TEXT NOT NULL DEFAULT 'manual',
                created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE(meter_id, read_on)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS reading_values (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                reading_id BIGINT NOT NULL REFERENCES readings(id) ON DELETE CASCADE,
                register_id BIGINT NOT NULL REFERENCES registers(id) ON DELETE CASCADE,
                value NUMERIC(12,3) NOT NULL,
                UNIQUE(reading_id, register_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS login_links (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email_hash TEXT NOT NULL,
                token_hash TEXT NOT NULL UNIQUE,
                expires_at TIMESTAMPTZ NOT NULL,
                used_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                expires_at TIMESTAMPTZ NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS reminders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                house_id BIGINT NOT NULL REFERENCES houses(id) ON DELETE CASCADE,
                enabled BOOLEAN NOT NULL DEFAULT true,
                sent_on DATE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE(user_id, house_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS meter_orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                meter_id BIGINT NOT NULL REFERENCES meters(id) ON DELETE CASCADE,
                position INTEGER,
                color TEXT NOT NULL DEFAULT '',
                axis TEXT NOT NULL DEFAULT '',
                UNIQUE(user_id, meter_id)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS passkeys (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                credential_id TEXT NOT NULL UNIQUE,
                public_key TEXT NOT NULL,
                sign_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                last_used_at TIMESTAMPTZ
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS sensors (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                house_id BIGINT NOT NULL REFERENCES houses(id) ON DELETE CASCADE,
                entity_id_sealed TEXT NOT NULL,
                entity_hash TEXT NOT NULL,
                name_sealed TEXT NOT NULL DEFAULT '',
                unit TEXT NOT NULL DEFAULT '',
                position INTEGER NOT NULL DEFAULT 0,
                active BOOLEAN NOT NULL DEFAULT true,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE(house_id, entity_hash)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS samples (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sensor_id BIGINT NOT NULL REFERENCES sensors(id) ON DELETE CASCADE,
                measured_at TIMESTAMPTZ NOT NULL,
                value NUMERIC(8,2) NOT NULL,
                UNIQUE(sensor_id, measured_at)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_login_links_email_hash ON login_links(email_hash)",
            "CREATE INDEX IF NOT EXISTS ix_sessions_token_hash ON sessions(token_hash)",
            "CREATE INDEX IF NOT EXISTS ix_user_houses_user_id ON user_houses(user_id)",
            "CREATE INDEX IF NOT EXISTS ix_meters_house_id ON meters(house_id)",
            "CREATE INDEX IF NOT EXISTS ix_readings_meter_id ON readings(meter_id)",
            "CREATE INDEX IF NOT EXISTS ix_reading_values_reading_id ON reading_values(reading_id)",
            "CREATE INDEX IF NOT EXISTS ix_sensors_house_id ON sensors(house_id)",
            "CREATE INDEX IF NOT EXISTS ix_samples_sensor_id_measured_at ON samples(sensor_id, measured_at)",
        ]
        for statement in statements:
            connection.execute(statement)

    def _migrate(self, connection: psycopg.Connection[dict[str, Any]]) -> None:
        migrations: list[tuple[int, str]] = [
            (1, "initial encrypted usage schema"),
            (2, "per house monthly reminders"),
            (3, "three decimal reading values"),
            (4, "per user meter order"),
            (5, "per user meter colors"),
            (6, "merged graph axis per user"),
            (7, "monthly value meters"),
            (8, "house time zones"),
            (9, "home assistant sensors"),
        ]
        for version, name in migrations:
            row = connection.execute("SELECT 1 FROM schema_migrations WHERE version = %s", (version,)).fetchone()
            if row is None:
                if version == 9:
                    connection.execute("ALTER TABLE houses ADD COLUMN IF NOT EXISTS ingest_token_hash TEXT NOT NULL DEFAULT ''")
                if version == 8:
                    connection.execute("ALTER TABLE houses ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Europe/Paris'")
                if version == 7:
                    connection.execute("ALTER TABLE meters ADD COLUMN IF NOT EXISTS monthly BOOLEAN NOT NULL DEFAULT false")
                if version == 6:
                    connection.execute("ALTER TABLE meter_orders ADD COLUMN IF NOT EXISTS axis TEXT NOT NULL DEFAULT ''")
                if version == 5:
                    # A colour-only row must not hijack the order: position becomes optional.
                    connection.execute("ALTER TABLE meter_orders ALTER COLUMN position DROP NOT NULL")
                    connection.execute("ALTER TABLE meter_orders ALTER COLUMN position DROP DEFAULT")
                    connection.execute("ALTER TABLE meter_orders ADD COLUMN IF NOT EXISTS color TEXT NOT NULL DEFAULT ''")
                if version == 3:
                    # Widening only: both colours keep reading the values during the overlap.
                    connection.execute("ALTER TABLE registers ALTER COLUMN initial_value TYPE NUMERIC(12,3)")
                    connection.execute("ALTER TABLE reading_values ALTER COLUMN value TYPE NUMERIC(12,3)")
                connection.execute(
                    "INSERT INTO schema_migrations(version, name) VALUES (%s, %s)",
                    (version, name),
                )

    def _seed(self, connection: psycopg.Connection[dict[str, Any]]) -> None:
        self._seed_initial_admin(connection)

    def _seed_initial_admin(self, connection: psycopg.Connection[dict[str, Any]]) -> None:
        email = Constants.first_admin_email
        email_hash = self.blind_index(email)
        user = connection.execute("SELECT id FROM users WHERE email_hash = %s", (email_hash,)).fetchone()
        if user is None:
            connection.execute(
                """
                INSERT INTO users(email_sealed, email_hash, name_sealed, is_admin)
                VALUES (%s, %s, %s, true)
                """,
                (self.encrypt(email), email_hash, self.encrypt(Constants.first_admin_name)),
            )
            return
        connection.execute("UPDATE users SET is_admin = true WHERE id = %s", (int(user["id"]),))
